# Generated by Django 2.2.5 on 2019-10-01 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_auto_20191001_1727"),
        ("users", "0002_remove_student_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="tasks.Task",
            ),
        )
    ]
