# Generated by Django 2.2.5 on 2019-10-02 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='task',
        ),
    ]
