# Generated by Django 2.2.6 on 2019-10-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "qualis",
                    models.CharField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                            ("C3", "C3"),
                            ("C4", "C4"),
                            ("C5", "C5"),
                            ("", "Does not apply"),
                        ],
                        max_length=10,
                    ),
                ),
                ("deadline", models.DateField()),
                ("is_done", models.BooleanField(default=False)),
            ],
            options={"abstract": False},
        )
    ]
