# Generated by Django 2.2.8 on 2020-01-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20191023_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='qualis',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('C', 'C'), ('', 'Does not apply')], max_length=10),
        ),
    ]
