# Generated by Django 2.2.8 on 2020-01-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200115_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Periodic'), ('2', 'National Conference'), ('3', 'International Conference'), ('4', 'Journal'), ('4', 'Workshops'), ('5', 'Seminars'), ('6', 'Others')], max_length=20, null=True),
        ),
    ]
