# Generated by Django 2.2.6 on 2019-10-11 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("events", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("0", "In Writting Process"),
                            ("1", "Not yet defined"),
                            ("2", "Pending"),
                            ("3", "Under Revision"),
                            ("4", "Accepted"),
                            ("5", "Rejected"),
                        ],
                        default="0",
                        max_length=2,
                    ),
                ),
                ("paper_url", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.Event",
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
