# Generated by Django 2.2.5 on 2019-10-06 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0010_auto_20191001_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('1', 'Under Revision'), ('2', 'Accepted'), ('3', 'Denied')], max_length=2)),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('tasks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
