# Generated by Django 2.2.5 on 2019-10-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('1', 'Under Revision'), ('2', 'Accepted'), ('3', 'Denied')], default='1', max_length=2),
        ),
    ]
