# Generated by Django 2.2.6 on 2019-10-11 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='events.Event'),
        ),
    ]
