# Generated by Django 2.2.6 on 2019-10-11 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20191010_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Event'),
        ),
    ]
