# Generated by Django 2.2.5 on 2019-10-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20191006_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='tasks',
            new_name='task',
        ),
    ]
