# Generated by Django 2.2.6 on 2019-10-24 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20191010_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='paper_acronym',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('0', 'In Writting Process'), ('1', 'Not yet defined'), ('2', 'Under Revision'), ('3', 'Accepted'), ('4', 'Rejected')], default='0', max_length=2),
        ),
    ]
