# Generated by Django 2.2.6 on 2019-10-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20191006_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='paper_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('0', 'In Writting Process'), ('1', 'Not yet defined'), ('2', 'Pending'), ('3', 'Under Revision'), ('4', 'Accepted'), ('5', 'Rejected')], default='0', max_length=2),
        ),
    ]
