# Generated by Django 2.2.6 on 2019-10-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_auto_20191024_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submitted',
        ),
    ]
