# Generated by Django 2.2.6 on 2019-10-24 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_remove_submission_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='first_author',
        ),
        migrations.AlterField(
            model_name='submission',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
