# Generated by Django 2.2.6 on 2019-10-24 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_auto_20191024_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='students',
            field=models.ManyToManyField(related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
