# Generated by Django 2.2.8 on 2020-01-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_auto_20191024_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='paper_acronym',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('0', 'In Writting Process'), ('1', 'Not submitted'), ('2', 'Under Revision'), ('3', 'Accepted'), ('4', 'Rejected')], default='0', max_length=2),
        ),
    ]
