# Generated by Django 2.2.8 on 2020-01-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_auto_20200114_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='presentation_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='rebuttal_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='paper_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
