# Generated by Django 2.2.8 on 2020-01-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_auto_20200118_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='paper_acronym',
            field=models.CharField(max_length=100),
        ),
    ]
