# Generated by Django 2.2.8 on 2020-01-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_auto_20200118_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='progress_percentage',
        ),
    ]
