# Generated by Django 2.2.8 on 2020-01-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_remove_submission_progress_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='paper_reusults_done',
            new_name='paper_results_done',
        ),
    ]
