# Generated by Django 2.2.5 on 2019-09-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=200)),
                ("qualis", models.CharField(max_length=10)),
                ("deadline", models.DateField()),
            ],
        )
    ]
