# Generated by Django 2.2.5 on 2019-10-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tasks", "0007_auto_20190930_0943")]

    operations = [
        migrations.AddField(
            model_name="task",
            name="event_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(name="StudentHasTask"),
    ]
